import { readFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { base64ToBytes } from '../../src/core/encoding.js';
import type { WebhookCredentials } from '../../src/core/types.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

export interface Fixture {
  readonly provider: string;
  /** true = generated by createTestSigner, not a real captured delivery. See README.md. */
  readonly synthetic: boolean;
  readonly note?: string;
  readonly credentials: WebhookCredentials;
  readonly headers: Record<string, string>;
  readonly url?: string;
  readonly method?: string;
  readonly bodyBase64: string;
  readonly expected: { readonly eventId: string | null; readonly timestamp: number | null };
}

export interface LoadedFixture extends Fixture {
  readonly body: Uint8Array;
}

export function loadFixture(provider: string, name: string): LoadedFixture {
  const filePath = path.join(__dirname, provider, `${name}.json`);
  const raw = JSON.parse(readFileSync(filePath, 'utf8')) as Fixture;
  return { ...raw, body: base64ToBytes(raw.bodyBase64) };
}
